name: IntegrationTests

on:
  push:
    branches:
      - main
      - '[1-9].*.x'
  pull_request:
  workflow_dispatch:

jobs:
  TestBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: View versions
        run: |
          node -v
          npm -v
          yarn -v

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          npm run build
          npm run export
